name = "Here"
uuid = "d369ecc7-d25b-440f-ae65-7e57382d5ce8"
authors = ["Johan Larsson <johanlarsson@outlook.com> and contributors"]
version = "0.1.0"

[deps]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"

[compat]
FilePathsBase = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
