name = "Here"
uuid = "d369ecc7-d25b-440f-ae65-7e57382d5ce8"
authors = ["Johan Larsson <johanlarsson@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
